services:

  filter.expression_builder:
    class:  Slmder\SlmderFilterBundle\Filtration\Common\ExpressionBuilder
    arguments:
      ['@doctrine.orm.entity_manager']

  filter.static_availability_checker:
    tags: ['filter.availability_checker']
    class:  Slmder\SlmderFilterBundle\Filtration\Common\Field\Impl\StaticFieldAvailabilityChecker

  filter.entity_info:
    class:  Slmder\SlmderFilterBundle\Filtration\Common\EntityInfo
    arguments:
      ['@doctrine.orm.entity_manager']

  filter.join_maker:
    class:  Slmder\SlmderFilterBundle\Filtration\Common\JoinMaker
    arguments:
      ['@filter.entity_info','slmder_filter.checkers_enabled']

  filter.path_provider:
    class:  Slmder\SlmderFilterBundle\Filtration\Common\PropertyPathProvider\Impl\PropertyPathProvider
    arguments:
      ['%slmder_filter.default_operator%']

  filter.disjunction_strategy:
    class:  Slmder\SlmderFilterBundle\Filtration\QueryHandlerStrategy\Impl\DisjunctionQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider', '%slmder_filter.default_operator%']

  filter.simple_filter_strategy:
    class:  Slmder\SlmderFilterBundle\Filtration\QueryHandlerStrategy\Impl\ConjunctionFilterQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider','%slmder_filter.default_operator%']

  filter.sort_strategy:
    class:  Slmder\SlmderFilterBundle\Filtration\QueryHandlerStrategy\Impl\SortQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider','%slmder_filter.default_order_direction%']

  filter.query_builder_manager:
    class: Slmder\SlmderFilterBundle\Filtration\QueryBuilderManager
    arguments:
      ['@request_stack', '@filter.disjunction_strategy', '@filter.simple_filter_strategy', '@filter.sort_strategy']

  filter.filtration_subscriber:
    class: Slmder\SlmderFilterBundle\Filtration\EventListener\KnpPaginationSubscriber
    tags: ['kernel.event_subscriber']
    arguments:
      ['@filter.query_builder_manager','slmder_filter.trigger_on_pagination_items']

