services:

  filter.expression_builder:
    class:  Gns\GnsFilterBundle\Filtration\Common\ExpressionBuilder
    arguments:
      ['@doctrine.orm.entity_manager']

  filter.static_availability_checker:
    tags: ['filter.availability_checker']
    class:  Gns\GnsFilterBundle\Filtration\Common\Field\Impl\StaticFieldAvailabilityChecker

  filter.entity_info:
    class:  Gns\GnsFilterBundle\Filtration\Common\EntityInfo
    arguments:
      ['@doctrine.orm.entity_manager']

  filter.join_maker:
    class:  Gns\GnsFilterBundle\Filtration\Common\JoinMaker
    arguments:
      ['@filter.entity_info','gns_filter.checkers_enabled']

  filter.path_provider:
    class:  Gns\GnsFilterBundle\Filtration\Common\PropertyPathProvider\Impl\PropertyPathProvider
    arguments:
      ['%gns_filter.default_operator%']

  filter.disjunction_strategy:
    class:  Gns\GnsFilterBundle\Filtration\QueryHandlerStrategy\Impl\DisjunctionQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider', '%gns_filter.default_operator%']

  filter.simple_filter_strategy:
    class:  Gns\GnsFilterBundle\Filtration\QueryHandlerStrategy\Impl\ConjunctionFilterQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider','%gns_filter.default_operator%']

  filter.sort_strategy:
    class:  Gns\GnsFilterBundle\Filtration\QueryHandlerStrategy\Impl\SortQueryHandlerStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.join_maker', '@filter.expression_builder', '@filter.path_provider','%gns_filter.default_order_direction%']

  filter.include_strategy:
    class:  Gns\GnsFilterBundle\Filtration\QueryHandlerStrategy\Impl\Serializer\IncludeFieldsListExclusionStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.path_provider']

  filter.exclude_strategy:
    class:  Gns\GnsFilterBundle\Filtration\QueryHandlerStrategy\Impl\Serializer\ExcludeFieldsListExclusionStrategy
    tags: ['filter.handler_strategy']
    arguments:
      ['@filter.entity_info', '@filter.path_provider']

  filter.query_builder_manager:
    class: Gns\GnsFilterBundle\Filtration\QueryBuilderManager
    public: true
    arguments:
      ['@request_stack', '@filter.disjunction_strategy', '@filter.simple_filter_strategy', '@filter.sort_strategy']

